### ISSUE TITLE
Missing snippets for elixir-mode

### ISSUE THREAD

**Issue by radik909** [AndreaCrotti/yasnippet-snippets#164]
Reference: https://github.com/hisea/elixir-yasnippets/issues/3

After you included [elixir snippets](https://github.com/hisea/elixir-yasnippets) to the official collections, a commit with updated & additional snippets has been added https://github.com/hisea/elixir-yasnippets/commit/980ca7626c14ef0573bec0035ec7942796062783

Can you add those snippets or let me give a PR?

**Comment by AndreaCrotti** [comment]
Mm it's not really correct, I never copied snippets from that repository since I didn't get permission to.
You can see for yourself https://github.com/AndreaCrotti/yasnippet-snippets/tree/master/elixir-mode
where the current elixir snippets come from but it's from different sources.

So feel free to make a PR if you feel like you'd like to add something!
thanks
