### ISSUE TITLE
Add table snippets for markdown-mode

### ISSUE THREAD

**Issue by v0dro** [AndreaCrotti/yasnippet-snippets#263]
Being able to generate markdown tables using yasnippet would be nice.

**Comment by AndreaCrotti** [comment]
I think the problem with this is the ability to keep all the lines at the right length, which is what for example `org-mode` is capable of doing.

I don't think a simple snippet could really be able to do something as complicated unfortunately, and I normally just do tables with org-mode instead, so I'll close this for now since I don't think I can really give it a go.
