### ISSUE TITLE
in c++-mode some snippets don't work because they have a name conflict

### ISSUE THREAD

**Issue by guilhem-bichot** [AndreaCrotti/yasnippet-snippets#399]
Hello. Thanks for Yasnippet!
I noticed that in c++-mode, the snippets with keys "upr" and "tfm" have the same name "transform", thus one of them isn't expanded by my Emacs ("upr"); the same is true for the snippets with keys "vec" and "stv" which have the same name "vector".
This duplication is visible in this list http://andreacrotti.github.io/yasnippet-snippets/snippets.html .
Duplicate names inside a same mode are said to cause problems (here https://github.com/joaotavora/yasnippet/issues/548#issuecomment-68213893 and following).
Changing the name to avoid duplication, recompiling and reloading snippets fixes it in my case.
I'm using a yasnippet package downloaded from MELPA some time in September.

**Comment by guilhem-bichot** [comment]
There are other duplicated-names problems, in c++-mode and in other modes; here's a sample:
$ pwd
.../.emacs.d/elpa/yasnippet-snippets-20200909.1058/snippets

#Looking for duplicate names inside each subdirectory:

$ for dir in *; do echo "searching in $dir..." ; cat $dir/*|grep "# name:" | sort| uniq -d; done

# Here's a sample of the output:

searching in antlr-mode...
searching in applescript-mode...
…
searching in bibtex-mode...
# name: proceedings      < indicates that this name has at least two snippets
…
searching in c++-mode...
# name: accumulate
# name: cin
# name: copy
# name: cout
# name: d_operator<<
# name: generate_n
...
searching in emacs-lisp-mode...
# name: a function that process a file
# name: Command that works on region or word
…

**Comment by guilhem-bichot** [comment]
Alas, with Markdown my shell script line above looks corrupted; here it is again, properly:

` $ for dir in *; do echo "searching in $dir..." ; cat $dir/*|grep "# name:" | sort| uniq -d; done`

**Comment by abbaswasim** [comment]
I was looking for the same issue and found this, I had accidentally been using a workaround that I didn't know and just realised it.

In my case `vector` and `stv` are not behaving correctly that lead me to look for this issue. Only `stv` was loaded. 

I had some time ago copied the `vector` snippet into my own `~/.emacs/snippets` folder and even though it had the same name for some reason that works. This is still a work around I think and encourages duplication, the issue still remains that should be fixed in the snippets themselves.

**Comment by AndreaCrotti** [comment]
Thanks for the report @guilhem-bichot 
I think I'll improve the build pipeline for this project, to make sure this can't happen again (after I fix this issue).
